[package]
name = "rustyray"
version = "0.1.0"
authors = ["Quasar Jarosz <quasar@ja.rosz.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

